### ISSUE TITLE
Not clear from documentation if further configuration is required after plugin install

### ISSUE THREAD

**Issue by gluefactory** [dbaggott/newrelic-dropwizard#13]
I've just used NPI to install the newrelic-dropwizard plugin, but I'm unsure if I'm required to include some kind of javaagent in the parameters passed to my dropwizard applications, in order to start monitoring the application.

Once I have working diagnostics via the plugin, I can submit a PR for the README.md

**Comment by gluefactory** [comment]
For further information - I installed the plugin via NPI into one of our accounts last week and it only showed up under the Plugins section of the Newrelic UI this morning. I've now repeated the installation on a different account this morning and it's still now showing under the Plugins section of the Newrelic UI

**Comment by dbaggott** [comment]
@gluefactory, sorry for the slow reply, did you get this resolved?  And, as you may have already figured out by now, you do not need to modify the dropwizard application in any way.  The plugin operates by polling the dropwizard application for its state (health & metrics) via http.  So, where ever the plugin is being installed needs network access to the application(s) being monitored.  Additionally, the plugin needs to be configured with the addresses of the dropwizard applications.  But the NPI process should walk you through that.

**Comment by jwhipp** [comment]
I am a little stuck here too.

Mostly, I need to understand this property:

 "agents": "Create one entry per Dropwizard application to be monitored",

I am not sure what this is supposed to be set to.   Is this a friendly name or something specific?

Also 

    "adminPort": "Optional: port /metrics and /healthcheck requests are serviced from (defaults to 8081)",
    "adminPath": "Optional: Use to specify a non-standard admin url path (such as when serving multiple dropwizard applications from the same host/port). For example, if set to '/myApp', health checks would be made using '/myApp/healthcheck'"

I assume I can just delete these if I the port and path are default?

Overall, I'd recommend updating the readme and just giving an example of what these should be for us dropwizard newbs.

**Comment by dbaggott** [comment]
@jwhipp the optional adminPort and adminPath can be deleted if you are using the default.

The `agents` property should be an array of one or more json objects.  Each agent object in the array should have a `host` property which is the network address that the application can be reached on.  The `name` property is for  the New Relic UI and, if not provided, defaults to the `host` value.

```
{
  "_comments": {
    "agents": "Create one entry per Dropwizard application to be monitored",
    "host": "REQUIRED: the host/ip of the Dropwizard application to be monitored",
    "name": "Optional: Dropwizard application name to display within New Relic dashboard UI (defaults to 'host')",
    "adminPort": "Optional: port /metrics and /healthcheck requests are serviced from (defaults to 8081)",
    "adminPath": "Optional: Use to specify a non-standard admin url path (such as when serving multiple dropwizard applications from the same host/port). For example, if set to '/myApp', health checks would be made using '/myApp/healthcheck'"
  },
  "agents": [
    {
      "host": "localhost",
      "name": "AppName"
    }
  ]
}
```

So a configuration might look like

```
{
  "agents": [
    {
       "host": "dw.app.com",
       "name": "MainSite"
    }
}
```

The intent is that you use NPI to install the plugin which forces you to edit that configuration file which is meant to be self-documenting.  But, clearly that could use some improvement!

(In my final configuration example, I removed the `_comments` section but it's safe to leave that in for reference)

**Comment by dbaggott** [comment]
Added some, hopefully, clarifying comments at https://github.com/dbaggott/newrelic-dropwizard/blob/master/README.md#installation

Closing this for now, feel free to reopen if it still feels confusing.
